version: "3.8"
services:
  vote:
    build: ./vote
    depends_on:
      - redis
    ports: 
      - "80:80"
    networks:
      - frontend
      - backend
  redis:
    image: redis
    restart: always
    depends_on:
      - worker
    volumes:
        - redis_data:/data
    networks:
      - backend
  worker:
    build: ./worker
    depends_on:
      - db
    networks:
      - backend
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    depends_on:
      - result
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
  result:
    build: ./result
    ports:
      - "81:80"
    networks:
      - frontend
      - backend

volumes:
    postgres_data:
    redis_data:

networks:
  frontend:
  backend:
